version: '3'

services:

  nginx-waf:
    build:
      context: .
      dockerfile: v3-nginx/Dockerfile
    environment:
      BACKEND: http://frontend:81
      PORT: "80"
      SSL_PORT: "443"
      # DNS_SERVER: "8.8.8.8"
      METRICS_ALLOW_FROM: all
    ports:
    - "80:80"
    - "443:443"
    user: "10001"
    networks:
      - frontend

  frontend:
    image: echo/nginx-app-server
    build: 
      context: ../echo-fed-server
    ports:
      - "81:81"
    networks:
      - frontend
      - backend

  backend:
    image: echo/app-resource-server
    environment:
      - JASYPT_ENCRYPT_KEY
    build:
      context: ../echo-webapp-resource
    networks:
      - backend

networks:
  frontend:
  backend: