version: '3'

services:

  nginx-waf:
    build:
      context: .
      dockerfile: v3-nginx/Dockerfile
    environment:
      BACKEND: http://frontend:81
      PORT: "80"
      SSL_PORT: "443"
      METRICS_ALLOW_FROM: all
      PROXY_SSL_CERT: /etc/cert/echobankagent/fullchain.pem
      PROXY_SSL_CERT_KEY: /etc/cert/echobankagent/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/cert/cloudflare/echobankagent:/etc/cert/echobankagent
    networks:
      - net-frontend # ensures this can only see 'app-frontend'
    depends_on:
      - frontend

  frontend:
    image: echo/nginx-app-server
    build: 
      context: ./echo-fed-server
    depends_on:
      - backend
    networks:
      - net-frontend  # can see itself, as well as ...
      - net-backend   # the 'app-backend' service

  backend:
    image: echo/spring-resource-server
    environment:
      - JASYPT_ENCRYPT_KEY
    build:
      context: ./echo-webapp-resource
    networks:
      - net-backend   # can see itself, and ...
      - net-database  # the app-database service
    depends_on:
      - database

  database:
    image: mysql:5.7.32
    volumes:
      - /etc/mysql-custom:/etc/mysql/conf.d
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"   # only expose container port.
    networks:
      - net-database

# Only services (nginx-waf, frontend, backend, database) which are
# registered in given network can access each other using the
# target's service name.

# e.g. 'backend' can access the db using hostname 'database' since
# they both declare 'net-database' 

networks:
  net-frontend:
  net-backend:
  net-database:

